### ISSUE TITLE
Is the word "Whisper" intended ?

### ISSUE THREAD

**Issue by 8f5506c4979a** [vergecurrency/Verge-Blackpaper#17]
Is the word "Whisper" intended in the line 4 of the page 13 of your black paper ?

> Whisper utilizes The Elliptic Curve Digital Signature Algorithm, ... 

Your encrypted chat is called "Visp" right ? isn't the one fron ethereum called "Whisper" ?

**Comment by ghost** [comment]
Ah, yes this was an oversight on my part as we were going to originally
call it whisper but thought it not unique enough. Good catch, I'll make the
change in the a.m

Cheers!

**Comment by Technophant** [comment]
What does Visp stand for?
